sonar.projectKey=MC307656_PracticoSonarQube
sonar.organization=mc307656

# Nombre de la app que se muestra en la web de SonarCloud
sonar.projectName=PracticoSonarQube
sonar.projectVersion=1.0

# Indica que analice todo el código partiendo de la raíz del proyecto
sonar.sources=.

# Codificación de archivos
sonar.sourceEncoding=UTF-8

# Exclusiones (opcional, ignora archivos de test)
sonar.exclusions=**/*test*/**
